### ISSUE TITLE
Performance Benchmarking 

### ISSUE THREAD

**Issue by daria-github** [xmtp-labs/xmtp-inbox-web#399]
Tracking ticket to add perf benchmarking tests for large # of conversations and large # of messages within a conversation.

**Comment by neekolas** [comment]
We do have per-conversation benchmarking around ecryption/decryption in `xmtp-js` [here](https://github.com/xmtp/xmtp-js/tree/main/bench). This is obviously a little different, since the DB is involved, but might save some time if you can avoid duplicative benchmarks. And of course, feel free to add to the benchmarking suite in that folder if there's something you want to measure that isn't `xmtp-js` specific..

**Comment by rygine** [comment]
closing for now because this app is in maintenance mode.
